name: Performance Regression Tests
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run julia benchmark example
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: runner.os−test−env.cache−name−{{ hashFiles('**/Project.toml') }}
          restore-keys: |
            runner.os−test−
            ${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Run benchmark
        run: |
          julia --project=GalerkinToolkitExamples -e '
            using Pkg
            Pkg.develop(path=".")
            include("GalerkinToolkitExamples/benchmarks/run_benchmarks.jl")'
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Julia benchmark result
          tool: 'julia'
          output-file-path: output.json
          gh-pages-branch: benchmarks
          benchmark-data-dir-path: bench
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true

  copybenchmarks:
    name: Copy benchmark results to gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Checkout benchmarks branch
        uses: actions/checkout@v4
        with:
          ref: benchmarks
          path: benchmarks
      - name: Copy benchmark results to gh-pages
        run: |
          echo "---"
          ls
          echo "---"
          ls benchmarks/bench
          echo "---"
          ls gh-pages/dev
          cd gh-pages/dev
          cp -r benchmarks/bench gh-pages/dev/
          cd gh-pages
          git status
          git branch
          git add -A
          git status
          git commit -m 'Copy benchmark results to documentation on gh-pages'
          git status
          git push
